from snakemake.remote.FTP import RemoteProvider as FTPRemoteProvider
FTP = FTPRemoteProvider()

rule download_reference_genome:
    input:
        FTP.remote("ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz", keep_local=True)
    output:
        "../data/reference/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna"
    shell:
        "gunzip -c {input} > {output}"


rule index_reference_genome:
    input: 
        "../data/reference/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna"
    output:
        "../data/reference/GRCh38_no_alt_analysis_set"
    log:
        "../data/reference/gem_indexing.log"
    conda:
        "gem3"
    shell:
        "gem-indexer -i {input} -o {output}"