from snakemake.remote.FTP import RemoteProvider as FTPRemoteProvider
FTP = FTPRemoteProvider()

rule download_reference_genome:
    input:
        FTP.remote("ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz", keep_local=True)
    output:
        "../data/reference/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna"
    shell:
        "gunzip -c {input} > {output}"

index_reference_genome_out = ['hsapiens_v38.gem', 'hsapiens_v38.info']

rule index_reference_genome:
    input: 
        "../data/reference/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna"
    output:
        expand("../data/reference/{out}", out = index_reference_genome_out)
    params:
        prefix = "../data/reference/hsapiens_v38"
    log:
        "../logs/index_reference_genome/gem_indexing.log"
    conda:
        "gem3"
    shell:
        "gem-indexer -i {input} -o {params.prefix}"


rule gem3_map:
    input:
        "../data/reference/hsapiens_v38.BS.gem",
        "../data/samples/{sample_id}_sampled_R1_001.fq.gz",
        "../data/samples/{sample_id}_sampled_R2_001.fq.gz",
    output:
        "../data/samples-mapped/{sample_id}.bam"
    log:
        "../logs/gem3_map/{sample_id}.log"
    threads: 6
    conda: "gem3"
    shell:
        "gem-mapper -I {input[0]} -t {threads} -1 {input[1]} -2 {input[2]} -o {output}"

